Ejercicio 1 — Ventas totales de marzo

Filtra el dataset para quedarte solo con marzo y calcula las ventas totales del mes. Compara el resultado con el de febrero, que se vio en clase ($424.650). Antes de calcular, revisa si hay algo en los datos que debería excluirse de una venta "neta" (devoluciones, cancelaciones) — si no hay ninguna columna que indique eso, acláralo como supuesto en tu respuesta.

In [3]:
import pandas as pd

# Cargar el archivo 
df = pd.read_csv('../ventas_kiosco.csv')

# 1. Asegurarnos de que la columna 'fecha' (en minúscula) sea interpretada como fecha
df['fecha'] = pd.to_datetime(df['fecha'])

# 2. Filtrar el DataFrame para quedarnos solo con el mes de marzo (mes 3)
df_marzo = df[df['fecha'].dt.month == 3].copy()

# 3. Crear una nueva columna con el total multiplicando 'cantidad' y 'precio_unitario'
df_marzo['Total_Venta'] = df_marzo['cantidad'] * df_marzo['precio_unitario']

# 4. Sumar toda la columna para obtener el total mensual
ventas_totales_marzo = df_marzo['Total_Venta'].sum()

# 5. Mostrar el resultado para compararlo con febrero ($424.650)
print(f"Las ventas totales netas de marzo fueron: ${ventas_totales_marzo:,.2f}")

Las ventas totales netas de marzo fueron: $440,650.00


In [4]:
print(df.columns)

Index(['fecha', 'cliente', 'producto', 'cantidad', 'precio_unitario'], dtype='str')


Ejercicio 2 — Ticket promedio de marzo
Con el resultado del Ejercicio 1 y la cantidad de compras de marzo, calcula el ticket promedio. Compáralo con el de febrero (~$2.831). Calcula también la mediana de las ventas de marzo y compara ambos valores — si son muy distintos, explica qué podría estar causando esa diferencia.

In [5]:
# 1. Calcular el ticket promedio (la media)
ticket_promedio_marzo = df_marzo['Total_Venta'].mean()

# 2. Calcular la mediana de las ventas
mediana_marzo = df_marzo['Total_Venta'].median()

# 3. Mostrar los resultados para compararlos
print(f"Ticket Promedio de marzo (Media): ${ticket_promedio_marzo:,.2f}")
print(f"Mediana de ventas de marzo: ${mediana_marzo:,.2f}")

Ticket Promedio de marzo (Media): $2,937.67
Mediana de ventas de marzo: $2,100.00


Ejercicio 3 — Clientes únicos y clientes nuevos
Cuenta cuántos clientes únicos compraron en marzo. Identifica cuáles no habían comprado en febrero (clientes nuevos). Además, calcula cuántas compras hizo cada cliente en el período completo (groupby("cliente").size()) e indica si el negocio depende más de clientes que vuelven o de clientes que compran una sola vez.

In [6]:
# 1. Separar los datos de febrero (asumiendo que df_marzo ya lo tenemos)
df_febrero = df[df['fecha'].dt.month == 2]

# Obtener las listas de clientes únicos de cada mes
clientes_marzo = df_marzo['cliente'].unique()
clientes_febrero = df_febrero['cliente'].unique()

# Contar cuántos únicos hubo en marzo
cant_clientes_marzo = len(clientes_marzo)

# 2. Identificar clientes nuevos (están en marzo pero NO en febrero)
# Usamos conjuntos (sets) en Python para restar las listas fácilmente
clientes_nuevos = set(clientes_marzo) - set(clientes_febrero)
cant_clientes_nuevos = len(clientes_nuevos)

# 3. Calcular la cantidad de compras por cliente en TODO el período
compras_por_cliente = df.groupby('cliente').size()

# Calcular cuántos son de compra única y cuántos son recurrentes para sacar la conclusión
clientes_una_vez = (compras_por_cliente == 1).sum()
clientes_recurrentes = (compras_por_cliente > 1).sum()

# 4. Mostrar todos los resultados
print(f"Cantidad de clientes únicos en marzo: {cant_clientes_marzo}")
print(f"Cantidad de clientes nuevos en marzo: {cant_clientes_nuevos}")
print("-" * 40)
print(f"Clientes que compraron una sola vez: {clientes_una_vez}")
print(f"Clientes que volvieron a comprar (recurrentes): {clientes_recurrentes}")
print("-" * 40)
print("Detalle de compras por cliente (Muestra de los primeros 10):")
print(compras_por_cliente.head(10))

Cantidad de clientes únicos en marzo: 31
Cantidad de clientes nuevos en marzo: 16
----------------------------------------
Clientes que compraron una sola vez: 0
Clientes que volvieron a comprar (recurrentes): 41
----------------------------------------
Detalle de compras por cliente (Muestra de los primeros 10):
cliente
Cliente_01     6
Cliente_02     4
Cliente_03    10
Cliente_04    10
Cliente_05     7
Cliente_06     7
Cliente_07    11
Cliente_08    12
Cliente_09     2
Cliente_10    12
dtype: int64


Ejercicio 4 — Tasa de churn de febrero a marzo
De los clientes que compraron en febrero, cuenta cuántos no volvieron a comprar en marzo. Calcula la tasa de churn. Antes de calcularla, escribe en una oración qué ventana de tiempo estás asumiendo como "cliente perdido" y por qué te parece razonable para este negocio.

Identificar  a los clientes unicos de Febrero


In [13]:
import pandas as pd
import tkinter as tk
from tkinter import filedialog

# 1. Abrir ventana de Windows para buscar el archivo manualmente
root = tk.Tk()
root.attributes('-topmost', True)
root.withdraw() 
ruta_exacta = filedialog.askopenfilename(title="Busca y selecciona tu archivo ventas_kiosco")

print(f"La ruta real de tu archivo es: {ruta_exacta}")

# 2. Cargar el archivo (Volvemos a read_csv)
try:
    # Intentamos leerlo como un CSV normal
    df = pd.read_csv(ruta_exacta) 
except Exception:
    # Si falla, intentamos leerlo con separador de punto y coma
    df = pd.read_csv(ruta_exacta, sep=';')

df['fecha'] = pd.to_datetime(df['fecha'])

# 3. Cálculo de Churn
clientes_febrero = df[df['fecha'].dt.month == 2]['cliente'].unique()
clientes_marzo = df[df['fecha'].dt.month == 3]['cliente'].unique()

clientes_perdidos = set(clientes_febrero) - set(clientes_marzo)

total_febrero = len(clientes_febrero)
total_perdidos = len(clientes_perdidos)

if total_febrero > 0:
    tasa_churn = (total_perdidos / total_febrero) * 100
else:
    tasa_churn = 0

print("-" * 30)
print(f"Total clientes únicos en febrero: {total_febrero}")
print(f"Clientes que no volvieron en marzo (Perdidos): {total_perdidos}")
print(f"Tasa de Churn: {tasa_churn:.2f}%")

La ruta real de tu archivo es: C:/Users/Giovanni/Desktop/data-analysis-course/modulo-5-analisis-aplicado/clase-20/ventas_kiosco.csv
------------------------------
Total clientes únicos en febrero: 25
Clientes que no volvieron en marzo (Perdidos): 10
Tasa de Churn: 40.00%


Ejercicio 5 — Lectura de negocio
Con los cuatro resultados anteriores organizados en una tabla, escribe de tres a cinco oraciones respondiendo: ¿el negocio mejoró de febrero a marzo? La respuesta debe apoyarse en los números, no en una impresión general, y debe mencionar al menos un indicador que contradiga o matice la conclusión principal (como se vio en clase con el ejemplo de churn vs. clientes nuevos).

El desempeño comercial del kiosco muestra una tendencia superficialmente positiva hacia marzo, destacando una sólida capacidad de adquisición al sumar 16 clientes nuevos y elevar la base total de 25 a 31 compradores únicos. Esta afluencia permitió consolidar una facturación mensual de $440,650.00. Sin embargo, este crecimiento aparente se ve severamente matizado por una crítica tasa de churn del 40.00%; esto revela que 10 de los 25 clientes de febrero no volvieron a comprar, lo que indica un problema estructural de retención que obliga al negocio a depender excesivamente de la atracción constante de nuevos usuarios para sostener sus ingresos."